version: '3'
networks:
  dashboard:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
services:
### NGINX Server #########################################
  nginx:
    restart: always
    build:
      context: ./nginx
      args:
        - CHANGE_SOURCE=false
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./backend/makeup/:/var/www/makeup:cached
      - ./wordpress/:/var/www/html:cached
      - ./frontend/dist/:/var/www/static:cached
      - ./pwa/xlsx-form/:/var/www/pwa/xlsxform:cached
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
      - go-stock
    networks:
      dashboard:
        ipv4_address: 172.20.0.2
  ### Dev go container #########################################      
  # go-stock:
  #   restart: always
  #   build:
  #     context: ./go
  #   volumes:
  #     - ./backend/stock/:/go/src/stock:cached
  #   ports:
  #     - "80"
  #   environment:
  #     - TZ=Asia/Taipei
  #   command: tail -f /dev/null
  #   networks:
  #     dashboard:
  #       ipv4_address: 172.20.0.3
  ### Prod go container #########################################      
  go-stock:
    restart: always
    build:
      context: ./go
    volumes:
      - ./backend/stock/:/go/src/stock:cached
    environment:
      - TZ=Asia/Taipei
    command: ./server.run start
    depends_on:
      - mysql
      - mongo
    networks:
      dashboard:
        ipv4_address: 172.20.0.3
  go-linebot:
    restart: always
    image: alpine:3.18
    volumes:
      - ./backend/linebot/:/tmp:cached
    environment:
      - TZ=Asia/Taipei
      - LINE_CHANNEL_SECRET=asd
      - LINE_CHANNEL_ACCESSTOKEN=66
    command: /tmp/server.run
    depends_on:
      - mysql
      - mongo
    networks:
      dashboard:
        ipv4_address: 172.20.0.11

  go-stock-schedule:
    restart: always
    build:
      context: ./go
    volumes:
      - ./backend/stock/:/go/src/stock:cached
    environment:
      - TZ=Asia/Taipei
    command: ./server.run schedule run
    depends_on:
      - mysql
      - mongo
    networks:
      dashboard:
        ipv4_address: 172.20.0.8
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - CHANGE_SOURCE=false
    volumes:
      - ./backend/makeup/:/var/www:cached
    environment:
      - TZ=Asia/Taipei
    networks:
      dashboard:
        ipv4_address: 172.20.0.4
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=latest
    environment:
      - MYSQL_DATABASE=dashboard
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Taipei
    volumes:
      - ~/.dashboard/data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      dashboard:
        ipv4_address: 172.20.0.5
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/.dashboard/data/mongo:/data/db
      - ~/.dashboard/data/mongo_config:/data/configdb
    networks:
      dashboard:
        ipv4_address: 172.20.0.6
  wordpress:
    depends_on:
      - mysql
    image: wordpress:php7.4-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: default
      WORDPRESS_DB_PASSWORD: secret
    user: "1000:1000"
    networks:
      dashboard:
        ipv4_address: 172.20.0.7
