// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package concrete

import (
	"github.com/google/wire"
	"stock/services"
)

// Injectors from wire.go:

// CreateStockService CreateStockService
func CreateStockConcrete() *StockConcrete {
	stockService := services.CreateStockService()
	stockConcrete := NewStockConcrete(stockService)
	return stockConcrete
}

// wire.go:

var (
	StockConcreteSet = wire.NewSet(NewStockConcrete, services.CreateStockService)
)
