// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/google/wire"
	"stock/repositories"
)

// Injectors from wire.go:

// CreateUserService CreateUserService
func CreateUserService() *UserService {
	userRepository := repositories.CreateUserRepository()
	userService := NewUserService(userRepository)
	return userService
}

// CreateStockService CreateStockService
func CreateStockService() *StockService {
	stockRepository := repositories.CreateStockRepository()
	stockService := NewStockService(stockRepository)
	return stockService
}

// wire.go:

var (
	UserServiceSet  = wire.NewSet(NewUserService, repositories.CreateUserRepository)
	StockServiceSet = wire.NewSet(NewStockService, repositories.CreateStockRepository)
)
