// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package controllers

import (
	"github.com/google/wire"
	"stock/services"
)

// Injectors from wire.go:

// CreateStockController CreateStockController
func CreateStockController() *StockController {
	stockService := services.CreateStockService()
	stockController := NewStockController(stockService)
	return stockController
}

// CreateXlsxController CreateXlsxController
func CreateXlsxController() *XlsxController {
	xlsxService := services.CreateXlsxService()
	xlsxController := NewXlsxController(xlsxService)
	return xlsxController
}

// wire.go:

var (
	StockControllerSet = wire.NewSet(NewStockController, services.CreateStockService)
	XlsxControllerSet  = wire.NewSet(NewXlsxController, services.CreateXlsxService)
)
