// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package repositories

import (
	"github.com/google/wire"
	"stock/database"
	"stock/mongodb"
)

// Injectors from wire.go:

// CreateUserRepository CreateUserRepository
func CreateUserRepository() *UserRepository {
	db := database.GetDB()
	userRepository := NewUserRepository(db)
	return userRepository
}

// CreateStockRepository CreateStockRepository
func CreateStockRepository() *StockRepository {
	db := database.GetDB()
	mongoDatabase := mongodb.GetMongoDB()
	stockRepository := NewStockRepository(db, mongoDatabase)
	return stockRepository
}

// wire.go:

var (
	UserRepositorySet  = wire.NewSet(NewUserRepository, database.GetDB)
	StockRepositorySet = wire.NewSet(NewStockRepository, database.GetDB, mongodb.GetMongoDB)
)
